name: "Deploy Main"

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: mss-boot-io/mss-boot-admin-ui-react/.github/workflows/deploy-cloudflare.yml@main
    with:
      stage: "prod"
    secrets:
      cf_api_token: ${{ secrets.cf_api_token }}